/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (cli-args.c)
 *  
 *  It has been AutoGen-ed  July  3, 2012 at 12:05:43 AM by AutoGen 5.16
 *  From the definitions    cli-args.def
 *  and the template file   options
 *
 * Generated from AutoOpts 36:4:11 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the gnutls-cli author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * The gnutls-cli program is copyrighted and licensed
 * under the following terms:
 *
 *  Copyright (C) 2000-2012 Free Software Foundation, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *
 *  gnutls-cli is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  gnutls-cli is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __doxygen__
#define OPTION_CODE_COMPILE 1
#include "cli-args.h"
#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
#define zCopyright      (gnutls_cli_opt_strs+0)
#define zLicenseDescrip (gnutls_cli_opt_strs+278)


#ifndef NULL
#  define NULL 0
#endif

/*
 *  gnutls-cli option static const strings
 */
static char const gnutls_cli_opt_strs[3367] =
/*     0 */ "gnutls-cli 3.0.21\n"
            "Copyright (C) 2000-2012 Free Software Foundation, all rights reserved.\n"
            "This is free software. It is licensed for use, modification and\n"
            "redistribution under the terms of the\n"
            "GNU General Public License, version 3 or later\n"
            "    <http://gnu.org/licenses/gpl.html>\n\0"
/*   278 */ "gnutls-cli is free software: you can redistribute it and/or modify it under\n"
            "the terms of the GNU General Public License as published by the Free\n"
            "Software Foundation, either version 3 of the License, or (at your option)\n"
            "any later version.\n\n"
            "gnutls-cli is distributed in the hope that it will be useful, but WITHOUT\n"
            "ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
            "FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for\n"
            "more details.\n\n"
            "You should have received a copy of the GNU General Public License along\n"
            "with this program.  If not, see <http://www.gnu.org/licenses/>.\n\0"
/*   887 */ "Enable debugging.\0"
/*   905 */ "DEBUG\0"
/*   911 */ "debug\0"
/*   917 */ "More verbose output\0"
/*   937 */ "VERBOSE\0"
/*   945 */ "verbose\0"
/*   953 */ "Enable trust on first use authentication\0"
/*   994 */ "TOFU\0"
/*   999 */ "no-tofu\0"
/*  1007 */ "no\0"
/*  1010 */ "Enable OCSP certificate verification\0"
/*  1047 */ "OCSP\0"
/*  1052 */ "no-ocsp\0"
/*  1060 */ "Establish a session and resume\0"
/*  1091 */ "RESUME\0"
/*  1098 */ "resume\0"
/*  1105 */ "Establish a session and rehandshake\0"
/*  1141 */ "REHANDSHAKE\0"
/*  1153 */ "rehandshake\0"
/*  1165 */ "Don't accept session tickets\0"
/*  1194 */ "NOTICKET\0"
/*  1203 */ "noticket\0"
/*  1212 */ "Connect, establish a plain session and start TLS.\0"
/*  1262 */ "STARTTLS\0"
/*  1271 */ "starttls\0"
/*  1280 */ "Use DTLS (datagram TLS) over UDP\0"
/*  1313 */ "UDP\0"
/*  1317 */ "udp\0"
/*  1321 */ "Set MTU for datagram TLS\0"
/*  1346 */ "MTU\0"
/*  1350 */ "mtu\0"
/*  1354 */ "Send CR LF instead of LF\0"
/*  1379 */ "CRLF\0"
/*  1384 */ "crlf\0"
/*  1389 */ "Use DER format for certificates to read from\0"
/*  1434 */ "X509FMTDER\0"
/*  1445 */ "x509fmtder\0"
/*  1456 */ "Send the openpgp fingerprint, instead of the key\0"
/*  1505 */ "FINGERPRINT\0"
/*  1517 */ "fingerprint\0"
/*  1529 */ "Disable all the TLS extensions\0"
/*  1560 */ "DISABLE_EXTENSIONS\0"
/*  1579 */ "disable-extensions\0"
/*  1598 */ "Print peer's certificate in PEM format\0"
/*  1637 */ "PRINT_CERT\0"
/*  1648 */ "print-cert\0"
/*  1659 */ "The maximum record size to advertize\0"
/*  1696 */ "RECORDSIZE\0"
/*  1707 */ "recordsize\0"
/*  1718 */ "Priorities string\0"
/*  1736 */ "PRIORITY\0"
/*  1745 */ "priority\0"
/*  1754 */ "Certificate file or PKCS #11 URL to use\0"
/*  1794 */ "X509CAFILE\0"
/*  1805 */ "x509cafile\0"
/*  1816 */ "CRL file to use\0"
/*  1832 */ "X509CRLFILE\0"
/*  1844 */ "x509crlfile\0"
/*  1856 */ "PGP Key file to use\0"
/*  1876 */ "PGPKEYFILE\0"
/*  1887 */ "pgpkeyfile\0"
/*  1898 */ "PGP Key ring file to use\0"
/*  1923 */ "PGPKEYRING\0"
/*  1934 */ "pgpkeyring\0"
/*  1945 */ "PGP Public Key (certificate) file to use\0"
/*  1986 */ "PGPCERTFILE\0"
/*  1998 */ "pgpcertfile\0"
/*  2010 */ "X.509 key file or PKCS #11 URL to use\0"
/*  2048 */ "X509KEYFILE\0"
/*  2060 */ "x509keyfile\0"
/*  2072 */ "X.509 Certificate file or PKCS #11 URL to use\0"
/*  2118 */ "X509CERTFILE\0"
/*  2131 */ "x509certfile\0"
/*  2144 */ "PGP subkey to use (hex or auto)\0"
/*  2176 */ "PGPSUBKEY\0"
/*  2186 */ "pgpsubkey\0"
/*  2196 */ "SRP username to use\0"
/*  2216 */ "SRPUSERNAME\0"
/*  2228 */ "srpusername\0"
/*  2240 */ "SRP password to use\0"
/*  2260 */ "SRPPASSWD\0"
/*  2270 */ "srppasswd\0"
/*  2280 */ "PSK username to use\0"
/*  2300 */ "PSKUSERNAME\0"
/*  2312 */ "pskusername\0"
/*  2324 */ "PSK key (in hex) to use\0"
/*  2348 */ "PSKKEY\0"
/*  2355 */ "pskkey\0"
/*  2362 */ "The port or service to connect to\0"
/*  2396 */ "PORT\0"
/*  2401 */ "port\0"
/*  2406 */ "Don't abort program if server certificate can't be validated\0"
/*  2467 */ "INSECURE\0"
/*  2476 */ "insecure\0"
/*  2485 */ "Benchmark individual ciphers\0"
/*  2514 */ "BENCHMARK_CIPHERS\0"
/*  2532 */ "benchmark-ciphers\0"
/*  2550 */ "Benchmark individual software ciphers (no hw acceleration)\0"
/*  2609 */ "BENCHMARK_SOFT_CIPHERS\0"
/*  2632 */ "benchmark-soft-ciphers\0"
/*  2655 */ "Benchmark ciphers and key exchange methods in TLS\0"
/*  2705 */ "BENCHMARK_TLS\0"
/*  2719 */ "benchmark-tls\0"
/*  2733 */ "Print a list of the supported algorithms and modes\0"
/*  2784 */ "LIST\0"
/*  2789 */ "list\0"
/*  2794 */ "Display extended usage information and exit\0"
/*  2838 */ "help\0"
/*  2843 */ "Extended usage information passed thru pager\0"
/*  2888 */ "more-help\0"
/*  2898 */ "Output version information and exit\0"
/*  2934 */ "version\0"
/*  2942 */ "GNUTLS_CLI\0"
/*  2953 */ "gnutls-cli - GnuTLS client - Ver. 3.0.21\n"
            "USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [hostname]\n\0"
/*  3063 */ "bug-gnutls@gnu.org\0"
/*  3082 */ "\n\n\0"
/*  3085 */ "\n"
            "Simple client program to set up a TLS connection to some other computer.  It\n"
            "sets up a TLS connection and forwards data from the standard input to the\n"
            "secured socket and vice versa.\n\0"
/*  3269 */ "gnutls-cli 3.0.21\0"
/*  3287 */ "Usage: gnutls-cli [options] hostname\n"
            "gnutls-cli --help for usage instructions.\n";

/*
 *  debug option description:
 */
#define DEBUG_DESC      (gnutls_cli_opt_strs+887)
#define DEBUG_NAME      (gnutls_cli_opt_strs+905)
#define DEBUG_name      (gnutls_cli_opt_strs+911)
#define DEBUG_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  verbose option description:
 */
#define VERBOSE_DESC      (gnutls_cli_opt_strs+917)
#define VERBOSE_NAME      (gnutls_cli_opt_strs+937)
#define VERBOSE_name      (gnutls_cli_opt_strs+945)
#define VERBOSE_FLAGS     (OPTST_DISABLED)

/*
 *  tofu option description:
 */
#define TOFU_DESC      (gnutls_cli_opt_strs+953)
#define TOFU_NAME      (gnutls_cli_opt_strs+994)
#define NOT_TOFU_name  (gnutls_cli_opt_strs+999)
#define NOT_TOFU_PFX   (gnutls_cli_opt_strs+1007)
#define TOFU_name      (NOT_TOFU_name + 3)
#define TOFU_FLAGS     (OPTST_DISABLED)

/*
 *  ocsp option description:
 */
#define OCSP_DESC      (gnutls_cli_opt_strs+1010)
#define OCSP_NAME      (gnutls_cli_opt_strs+1047)
#define NOT_OCSP_name  (gnutls_cli_opt_strs+1052)
#define NOT_OCSP_PFX   (gnutls_cli_opt_strs+1007)
#define OCSP_name      (NOT_OCSP_name + 3)
#define OCSP_FLAGS     (OPTST_DISABLED)

/*
 *  resume option description:
 */
#define RESUME_DESC      (gnutls_cli_opt_strs+1060)
#define RESUME_NAME      (gnutls_cli_opt_strs+1091)
#define RESUME_name      (gnutls_cli_opt_strs+1098)
#define RESUME_FLAGS     (OPTST_DISABLED)

/*
 *  rehandshake option description:
 */
#define REHANDSHAKE_DESC      (gnutls_cli_opt_strs+1105)
#define REHANDSHAKE_NAME      (gnutls_cli_opt_strs+1141)
#define REHANDSHAKE_name      (gnutls_cli_opt_strs+1153)
#define REHANDSHAKE_FLAGS     (OPTST_DISABLED)

/*
 *  noticket option description:
 */
#define NOTICKET_DESC      (gnutls_cli_opt_strs+1165)
#define NOTICKET_NAME      (gnutls_cli_opt_strs+1194)
#define NOTICKET_name      (gnutls_cli_opt_strs+1203)
#define NOTICKET_FLAGS     (OPTST_DISABLED)

/*
 *  starttls option description:
 */
#define STARTTLS_DESC      (gnutls_cli_opt_strs+1212)
#define STARTTLS_NAME      (gnutls_cli_opt_strs+1262)
#define STARTTLS_name      (gnutls_cli_opt_strs+1271)
#define STARTTLS_FLAGS     (OPTST_DISABLED)

/*
 *  udp option description:
 */
#define UDP_DESC      (gnutls_cli_opt_strs+1280)
#define UDP_NAME      (gnutls_cli_opt_strs+1313)
#define UDP_name      (gnutls_cli_opt_strs+1317)
#define UDP_FLAGS     (OPTST_DISABLED)

/*
 *  mtu option description:
 */
#define MTU_DESC      (gnutls_cli_opt_strs+1321)
#define MTU_NAME      (gnutls_cli_opt_strs+1346)
#define MTU_name      (gnutls_cli_opt_strs+1350)
#define MTU_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  crlf option description:
 */
#define CRLF_DESC      (gnutls_cli_opt_strs+1354)
#define CRLF_NAME      (gnutls_cli_opt_strs+1379)
#define CRLF_name      (gnutls_cli_opt_strs+1384)
#define CRLF_FLAGS     (OPTST_DISABLED)

/*
 *  x509fmtder option description:
 */
#define X509FMTDER_DESC      (gnutls_cli_opt_strs+1389)
#define X509FMTDER_NAME      (gnutls_cli_opt_strs+1434)
#define X509FMTDER_name      (gnutls_cli_opt_strs+1445)
#define X509FMTDER_FLAGS     (OPTST_DISABLED)

/*
 *  fingerprint option description:
 */
#define FINGERPRINT_DESC      (gnutls_cli_opt_strs+1456)
#define FINGERPRINT_NAME      (gnutls_cli_opt_strs+1505)
#define FINGERPRINT_name      (gnutls_cli_opt_strs+1517)
#define FINGERPRINT_FLAGS     (OPTST_DISABLED)

/*
 *  disable-extensions option description:
 */
#define DISABLE_EXTENSIONS_DESC      (gnutls_cli_opt_strs+1529)
#define DISABLE_EXTENSIONS_NAME      (gnutls_cli_opt_strs+1560)
#define DISABLE_EXTENSIONS_name      (gnutls_cli_opt_strs+1579)
#define DISABLE_EXTENSIONS_FLAGS     (OPTST_DISABLED)

/*
 *  print-cert option description:
 */
#define PRINT_CERT_DESC      (gnutls_cli_opt_strs+1598)
#define PRINT_CERT_NAME      (gnutls_cli_opt_strs+1637)
#define PRINT_CERT_name      (gnutls_cli_opt_strs+1648)
#define PRINT_CERT_FLAGS     (OPTST_DISABLED)

/*
 *  recordsize option description:
 */
#define RECORDSIZE_DESC      (gnutls_cli_opt_strs+1659)
#define RECORDSIZE_NAME      (gnutls_cli_opt_strs+1696)
#define RECORDSIZE_name      (gnutls_cli_opt_strs+1707)
#define RECORDSIZE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

/*
 *  priority option description:
 */
#define PRIORITY_DESC      (gnutls_cli_opt_strs+1718)
#define PRIORITY_NAME      (gnutls_cli_opt_strs+1736)
#define PRIORITY_name      (gnutls_cli_opt_strs+1745)
#define PRIORITY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  x509cafile option description:
 */
#define X509CAFILE_DESC      (gnutls_cli_opt_strs+1754)
#define X509CAFILE_NAME      (gnutls_cli_opt_strs+1794)
#define X509CAFILE_name      (gnutls_cli_opt_strs+1805)
#define X509CAFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  x509crlfile option description:
 */
#define X509CRLFILE_DESC      (gnutls_cli_opt_strs+1816)
#define X509CRLFILE_NAME      (gnutls_cli_opt_strs+1832)
#define X509CRLFILE_name      (gnutls_cli_opt_strs+1844)
#define X509CRLFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  pgpkeyfile option description:
 */
#define PGPKEYFILE_DESC      (gnutls_cli_opt_strs+1856)
#define PGPKEYFILE_NAME      (gnutls_cli_opt_strs+1876)
#define PGPKEYFILE_name      (gnutls_cli_opt_strs+1887)
#define PGPKEYFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  pgpkeyring option description:
 */
#define PGPKEYRING_DESC      (gnutls_cli_opt_strs+1898)
#define PGPKEYRING_NAME      (gnutls_cli_opt_strs+1923)
#define PGPKEYRING_name      (gnutls_cli_opt_strs+1934)
#define PGPKEYRING_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  pgpcertfile option description:
 */
#define PGPCERTFILE_DESC      (gnutls_cli_opt_strs+1945)
#define PGPCERTFILE_NAME      (gnutls_cli_opt_strs+1986)
#define PGPCERTFILE_name      (gnutls_cli_opt_strs+1998)
#define PGPCERTFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_FILE))

/*
 *  x509keyfile option description:
 */
#define X509KEYFILE_DESC      (gnutls_cli_opt_strs+2010)
#define X509KEYFILE_NAME      (gnutls_cli_opt_strs+2048)
#define X509KEYFILE_name      (gnutls_cli_opt_strs+2060)
#define X509KEYFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  x509certfile option description:
 */
#define X509CERTFILE_DESC      (gnutls_cli_opt_strs+2072)
#define X509CERTFILE_NAME      (gnutls_cli_opt_strs+2118)
#define X509CERTFILE_name      (gnutls_cli_opt_strs+2131)
#define X509CERTFILE_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  pgpsubkey option description:
 */
#define PGPSUBKEY_DESC      (gnutls_cli_opt_strs+2144)
#define PGPSUBKEY_NAME      (gnutls_cli_opt_strs+2176)
#define PGPSUBKEY_name      (gnutls_cli_opt_strs+2186)
#define PGPSUBKEY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  srpusername option description:
 */
#define SRPUSERNAME_DESC      (gnutls_cli_opt_strs+2196)
#define SRPUSERNAME_NAME      (gnutls_cli_opt_strs+2216)
#define SRPUSERNAME_name      (gnutls_cli_opt_strs+2228)
#define SRPUSERNAME_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  srppasswd option description:
 */
#define SRPPASSWD_DESC      (gnutls_cli_opt_strs+2240)
#define SRPPASSWD_NAME      (gnutls_cli_opt_strs+2260)
#define SRPPASSWD_name      (gnutls_cli_opt_strs+2270)
#define SRPPASSWD_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  pskusername option description:
 */
#define PSKUSERNAME_DESC      (gnutls_cli_opt_strs+2280)
#define PSKUSERNAME_NAME      (gnutls_cli_opt_strs+2300)
#define PSKUSERNAME_name      (gnutls_cli_opt_strs+2312)
#define PSKUSERNAME_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  pskkey option description:
 */
#define PSKKEY_DESC      (gnutls_cli_opt_strs+2324)
#define PSKKEY_NAME      (gnutls_cli_opt_strs+2348)
#define PSKKEY_name      (gnutls_cli_opt_strs+2355)
#define PSKKEY_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  port option description:
 */
#define PORT_DESC      (gnutls_cli_opt_strs+2362)
#define PORT_NAME      (gnutls_cli_opt_strs+2396)
#define PORT_name      (gnutls_cli_opt_strs+2401)
#define PORT_FLAGS     (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  insecure option description:
 */
#define INSECURE_DESC      (gnutls_cli_opt_strs+2406)
#define INSECURE_NAME      (gnutls_cli_opt_strs+2467)
#define INSECURE_name      (gnutls_cli_opt_strs+2476)
#define INSECURE_FLAGS     (OPTST_DISABLED)

/*
 *  benchmark-ciphers option description:
 */
#define BENCHMARK_CIPHERS_DESC      (gnutls_cli_opt_strs+2485)
#define BENCHMARK_CIPHERS_NAME      (gnutls_cli_opt_strs+2514)
#define BENCHMARK_CIPHERS_name      (gnutls_cli_opt_strs+2532)
#define BENCHMARK_CIPHERS_FLAGS     (OPTST_DISABLED)

/*
 *  benchmark-soft-ciphers option description:
 */
#define BENCHMARK_SOFT_CIPHERS_DESC      (gnutls_cli_opt_strs+2550)
#define BENCHMARK_SOFT_CIPHERS_NAME      (gnutls_cli_opt_strs+2609)
#define BENCHMARK_SOFT_CIPHERS_name      (gnutls_cli_opt_strs+2632)
#define BENCHMARK_SOFT_CIPHERS_FLAGS     (OPTST_DISABLED)

/*
 *  benchmark-tls option description:
 */
#define BENCHMARK_TLS_DESC      (gnutls_cli_opt_strs+2655)
#define BENCHMARK_TLS_NAME      (gnutls_cli_opt_strs+2705)
#define BENCHMARK_TLS_name      (gnutls_cli_opt_strs+2719)
#define BENCHMARK_TLS_FLAGS     (OPTST_DISABLED)

/*
 *  list option description:
 */
#define LIST_DESC      (gnutls_cli_opt_strs+2733)
#define LIST_NAME      (gnutls_cli_opt_strs+2784)
#define LIST_name      (gnutls_cli_opt_strs+2789)
#define LIST_FLAGS     (OPTST_DISABLED)

/*
 *  Help/More_Help/Version option descriptions:
 */
#define HELP_DESC       (gnutls_cli_opt_strs+2794)
#define HELP_name       (gnutls_cli_opt_strs+2838)
#ifdef HAVE_WORKING_FORK
#define MORE_HELP_DESC  (gnutls_cli_opt_strs+2843)
#define MORE_HELP_name  (gnutls_cli_opt_strs+2888)
#define MORE_HELP_FLAGS (OPTST_IMM | OPTST_NO_INIT)
#else
#define MORE_HELP_DESC  NULL
#define MORE_HELP_name  NULL
#define MORE_HELP_FLAGS (OPTST_OMITTED | OPTST_NO_INIT)
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define VER_FLAGS     (OPTST_IMM | OPTST_NO_INIT)
#else
#  define VER_FLAGS     (OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                         OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT)
#endif
#define VER_DESC        (gnutls_cli_opt_strs+2898)
#define VER_name        (gnutls_cli_opt_strs+2934)
/*
 *  Declare option callback procedures
 */
extern tOptProc
    optionBooleanVal,   optionNestedVal,    optionNumericVal,
    optionPagedUsage,   optionPrintVersion, optionResetOpt,
    optionStackArg,     optionTimeDate,     optionTimeVal,
    optionUnstackArg,   optionVendorOption;
static tOptProc
    doOptDebug,       doOptMtu,         doOptPgpcertfile, doOptPgpkeyfile,
    doOptPgpkeyring,  doOptRecordsize,  doOptX509crlfile, doUsageOpt;
#define VER_PROC        optionPrintVersion

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 *  Define the gnutls-cli Option Descriptions.
 * This is an array of OPTION_CT entries, one for each
 * option that the gnutls-cli program responds to.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_DEBUG,
     /* equiv idx, value */ 0, VALUE_OPT_DEBUG,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEBUG_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --debug */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptDebug,
     /* desc, NAME, name */ DEBUG_DESC, DEBUG_NAME, DEBUG_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_VERBOSE,
     /* equiv idx, value */ 1, VALUE_OPT_VERBOSE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ VERBOSE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --verbose */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ VERBOSE_DESC, VERBOSE_NAME, VERBOSE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_TOFU,
     /* equiv idx, value */ 2, VALUE_OPT_TOFU,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TOFU_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --tofu */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ TOFU_DESC, TOFU_NAME, TOFU_name,
     /* disablement strs */ NOT_TOFU_name, NOT_TOFU_PFX },

  {  /* entry idx, value */ 3, VALUE_OPT_OCSP,
     /* equiv idx, value */ 3, VALUE_OPT_OCSP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OCSP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --ocsp */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ OCSP_DESC, OCSP_NAME, OCSP_name,
     /* disablement strs */ NOT_OCSP_name, NOT_OCSP_PFX },

  {  /* entry idx, value */ 4, VALUE_OPT_RESUME,
     /* equiv idx, value */ 4, VALUE_OPT_RESUME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ RESUME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --resume */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ RESUME_DESC, RESUME_NAME, RESUME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 5, VALUE_OPT_REHANDSHAKE,
     /* equiv idx, value */ 5, VALUE_OPT_REHANDSHAKE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ REHANDSHAKE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --rehandshake */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ REHANDSHAKE_DESC, REHANDSHAKE_NAME, REHANDSHAKE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_NOTICKET,
     /* equiv idx, value */ 6, VALUE_OPT_NOTICKET,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NOTICKET_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --noticket */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ NOTICKET_DESC, NOTICKET_NAME, NOTICKET_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_STARTTLS,
     /* equiv idx, value */ 7, VALUE_OPT_STARTTLS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ STARTTLS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --starttls */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ STARTTLS_DESC, STARTTLS_NAME, STARTTLS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_UDP,
     /* equiv idx, value */ 8, VALUE_OPT_UDP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ UDP_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --udp */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ UDP_DESC, UDP_NAME, UDP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_MTU,
     /* equiv idx, value */ 9, VALUE_OPT_MTU,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MTU_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --mtu */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptMtu,
     /* desc, NAME, name */ MTU_DESC, MTU_NAME, MTU_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 10, VALUE_OPT_CRLF,
     /* equiv idx, value */ 10, VALUE_OPT_CRLF,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CRLF_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --crlf */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ CRLF_DESC, CRLF_NAME, CRLF_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_X509FMTDER,
     /* equiv idx, value */ 11, VALUE_OPT_X509FMTDER,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ X509FMTDER_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --x509fmtder */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ X509FMTDER_DESC, X509FMTDER_NAME, X509FMTDER_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_FINGERPRINT,
     /* equiv idx, value */ 12, VALUE_OPT_FINGERPRINT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ FINGERPRINT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --fingerprint */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ FINGERPRINT_DESC, FINGERPRINT_NAME, FINGERPRINT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 13, VALUE_OPT_DISABLE_EXTENSIONS,
     /* equiv idx, value */ 13, VALUE_OPT_DISABLE_EXTENSIONS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DISABLE_EXTENSIONS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --disable-extensions */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ DISABLE_EXTENSIONS_DESC, DISABLE_EXTENSIONS_NAME, DISABLE_EXTENSIONS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_PRINT_CERT,
     /* equiv idx, value */ 14, VALUE_OPT_PRINT_CERT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PRINT_CERT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --print-cert */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PRINT_CERT_DESC, PRINT_CERT_NAME, PRINT_CERT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_RECORDSIZE,
     /* equiv idx, value */ 15, VALUE_OPT_RECORDSIZE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ RECORDSIZE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --recordsize */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptRecordsize,
     /* desc, NAME, name */ RECORDSIZE_DESC, RECORDSIZE_NAME, RECORDSIZE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_PRIORITY,
     /* equiv idx, value */ 16, VALUE_OPT_PRIORITY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PRIORITY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --priority */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PRIORITY_DESC, PRIORITY_NAME, PRIORITY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_X509CAFILE,
     /* equiv idx, value */ 17, VALUE_OPT_X509CAFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ X509CAFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --x509cafile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ X509CAFILE_DESC, X509CAFILE_NAME, X509CAFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_X509CRLFILE,
     /* equiv idx, value */ 18, VALUE_OPT_X509CRLFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ X509CRLFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --x509crlfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptX509crlfile,
     /* desc, NAME, name */ X509CRLFILE_DESC, X509CRLFILE_NAME, X509CRLFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 19, VALUE_OPT_PGPKEYFILE,
     /* equiv idx, value */ 19, VALUE_OPT_PGPKEYFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PGPKEYFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pgpkeyfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptPgpkeyfile,
     /* desc, NAME, name */ PGPKEYFILE_DESC, PGPKEYFILE_NAME, PGPKEYFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_PGPKEYRING,
     /* equiv idx, value */ 20, VALUE_OPT_PGPKEYRING,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PGPKEYRING_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pgpkeyring */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptPgpkeyring,
     /* desc, NAME, name */ PGPKEYRING_DESC, PGPKEYRING_NAME, PGPKEYRING_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 21, VALUE_OPT_PGPCERTFILE,
     /* equiv idx, value */ 21, VALUE_OPT_PGPCERTFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PGPCERTFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pgpcertfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptPgpcertfile,
     /* desc, NAME, name */ PGPCERTFILE_DESC, PGPCERTFILE_NAME, PGPCERTFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_X509KEYFILE,
     /* equiv idx, value */ 22, VALUE_OPT_X509KEYFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ X509KEYFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --x509keyfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ X509KEYFILE_DESC, X509KEYFILE_NAME, X509KEYFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_X509CERTFILE,
     /* equiv idx, value */ 23, VALUE_OPT_X509CERTFILE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ X509CERTFILE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --x509certfile */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ X509CERTFILE_DESC, X509CERTFILE_NAME, X509CERTFILE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 24, VALUE_OPT_PGPSUBKEY,
     /* equiv idx, value */ 24, VALUE_OPT_PGPSUBKEY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PGPSUBKEY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pgpsubkey */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PGPSUBKEY_DESC, PGPSUBKEY_NAME, PGPSUBKEY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 25, VALUE_OPT_SRPUSERNAME,
     /* equiv idx, value */ 25, VALUE_OPT_SRPUSERNAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SRPUSERNAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --srpusername */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SRPUSERNAME_DESC, SRPUSERNAME_NAME, SRPUSERNAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_SRPPASSWD,
     /* equiv idx, value */ 26, VALUE_OPT_SRPPASSWD,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SRPPASSWD_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --srppasswd */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ SRPPASSWD_DESC, SRPPASSWD_NAME, SRPPASSWD_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 27, VALUE_OPT_PSKUSERNAME,
     /* equiv idx, value */ 27, VALUE_OPT_PSKUSERNAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PSKUSERNAME_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pskusername */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PSKUSERNAME_DESC, PSKUSERNAME_NAME, PSKUSERNAME_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 28, VALUE_OPT_PSKKEY,
     /* equiv idx, value */ 28, VALUE_OPT_PSKKEY,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PSKKEY_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --pskkey */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PSKKEY_DESC, PSKKEY_NAME, PSKKEY_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 29, VALUE_OPT_PORT,
     /* equiv idx, value */ 29, VALUE_OPT_PORT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ PORT_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --port */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ PORT_DESC, PORT_NAME, PORT_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 30, VALUE_OPT_INSECURE,
     /* equiv idx, value */ 30, VALUE_OPT_INSECURE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ INSECURE_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --insecure */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ INSECURE_DESC, INSECURE_NAME, INSECURE_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 31, VALUE_OPT_BENCHMARK_CIPHERS,
     /* equiv idx, value */ 31, VALUE_OPT_BENCHMARK_CIPHERS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BENCHMARK_CIPHERS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --benchmark-ciphers */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ BENCHMARK_CIPHERS_DESC, BENCHMARK_CIPHERS_NAME, BENCHMARK_CIPHERS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 32, VALUE_OPT_BENCHMARK_SOFT_CIPHERS,
     /* equiv idx, value */ 32, VALUE_OPT_BENCHMARK_SOFT_CIPHERS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BENCHMARK_SOFT_CIPHERS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --benchmark-soft-ciphers */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ BENCHMARK_SOFT_CIPHERS_DESC, BENCHMARK_SOFT_CIPHERS_NAME, BENCHMARK_SOFT_CIPHERS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 33, VALUE_OPT_BENCHMARK_TLS,
     /* equiv idx, value */ 33, VALUE_OPT_BENCHMARK_TLS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BENCHMARK_TLS_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --benchmark-tls */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ BENCHMARK_TLS_DESC, BENCHMARK_TLS_NAME, BENCHMARK_TLS_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 34, VALUE_OPT_LIST,
     /* equiv idx, value */ 34, VALUE_OPT_LIST,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LIST_FLAGS, 0,
     /* last opt argumnt */ { NULL }, /* --list */
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ LIST_DESC, LIST_NAME, LIST_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_VERSION,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ VER_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ VER_PROC,
     /* desc, NAME, name */ VER_DESC, NULL, VER_name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ HELP_DESC, NULL, HELP_name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, VALUE_OPT_MORE_HELP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ MORE_HELP_DESC, NULL, MORE_HELP_name,
     /* disablement strs */ NULL, NULL }
};


/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the gnutls-cli Option Environment
 */
#define zPROGNAME       (gnutls_cli_opt_strs+2942)
#define zUsageTitle     (gnutls_cli_opt_strs+2953)
#define zRcName         NULL
#define apzHomeList     NULL
#define zBugsAddr       (gnutls_cli_opt_strs+3063)
#define zExplain        (gnutls_cli_opt_strs+3082)
#define zDetail         (gnutls_cli_opt_strs+3085)
#define zFullVersion    (gnutls_cli_opt_strs+3269)
/* extracted from optcode.tlib near line 350 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE | OPTPROC_NXLAT_OPT
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define gnutls_cli_full_usage (NULL)

#define gnutls_cli_short_usage (gnutls_cli_opt_strs+3287)

#endif /* not defined __doxygen__ */

/*
 *  Create the static procedure(s) declared above.
 */
/**
 * The callout function that invokes the optionUsage function.
 *
 * @param pOptions the AutoOpts option description structure
 * @param pOptDesc the descriptor for the "help" (usage) option.
 * @noreturn
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    optionUsage(&gnutls_cliOptions, GNUTLS_CLI_EXIT_SUCCESS);
    /* NOTREACHED */
    (void)pOptDesc;
    (void)pOptions;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the debug option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptDebug(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0 ,  9999 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the mtu option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptMtu(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 17000 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the recordsize option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptRecordsize(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static struct {long rmin, rmax;} const rng[1] = {
        { 0, 4096 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the x509crlfile option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptX509crlfile(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the pgpkeyfile option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptPgpkeyfile(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the pgpkeyring option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptPgpkeyring(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/**
 * Code to handle the pgpcertfile option.
 *
 * @param pOptions the gnutls-cli options data structure
 * @param pOptDesc the option descriptor for this option.
 */
static void
doOptPgpcertfile(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static teOptFileType const  type =
        FTYPE_MODE_MUST_EXIST + FTYPE_MODE_NO_OPEN;
    static tuFileMode           mode;
#ifndef O_CLOEXEC
#  define O_CLOEXEC 0
#endif
    mode.file_flags = O_CLOEXEC;

    optionFileCheck(pOptions, pOptDesc, type, mode);
}
/* extracted from optmain.tlib near line 1113 */

/**
 * The directory containing the data associated with gnutls-cli.
 */
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

/**
 * Information about the person or institution that packaged gnutls-cli
 * for the current distribution.
 */
#ifndef  WITH_PACKAGER
# define gnutls_cli_packager_info NULL
#else
static char const gnutls_cli_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport gnutls_cli bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif
#ifndef __doxygen__

#endif /* __doxygen__ */
/**
 * The option definitions for gnutls-cli.  The one structure that
 * binds them all.
 */
tOptions gnutls_cliOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NEGATIONS
    + OPTPROC_REORDER
    + OPTPROC_GNUUSAGE
    + OPTPROC_MISUSE ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      NO_EQUIVALENT, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    38 /* full option count */, 35 /* user option count */,
    gnutls_cli_full_usage, gnutls_cli_short_usage,
    NULL, NULL,
    PKGDATADIR, gnutls_cli_packager_info
};

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

/**
 * AutoGen specific wrapper function for gettext.
 * It relies on the macro _() to convert from English to the target
 * language, then strdup-duplicates the result string.
 *
 * @param[in] pz the input text used as a lookup key.
 * @returns the translated text (if there is one),
 *   or the original text (if not).
 */
static char *
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(GNUTLS_CLI_EXIT_FAILURE);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/**
 * Translate all the translatable strings in the gnutls_cliOptions
 * structure defined above.  This is done only once.
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &gnutls_cliOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        coerce_it((void*)&(pOpt->pzShortUsage));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        gnutls_cliOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* cli-args.c ends here */
